(function () {
  const runtime = globalThis.__LINUXDO_PV__ && globalThis.__LINUXDO_PV__.runtime;
  if (!runtime) {
    return;
  }

  runtime.createInitialState = function createInitialState(deps) {
    const loadSettings = deps && deps.loadSettings;
    const loadCachedReactionOptions = deps && deps.loadCachedReactionOptions;
    const defaultReactionOptions = (deps && deps.defaultReactionOptions) || [];
    const locationHref = (deps && deps.locationHref) || "";

    return {
      root: null,
      header: null,
      title: null,
      meta: null,
      drawerBody: null,
      content: null,
      replyButton: null,
      jumpFirstPostButton: null,
      replyPanel: null,
      replyPanelTitle: null,
      replyTextarea: null,
      replySubmitButton: null,
      replyCancelButton: null,
      replyEmojiToggleButton: null,
      replyEmojiPanel: null,
      replyEmojiGrid: null,
      replyStatus: null,
      imagePreview: null,
      imagePreviewStage: null,
      imagePreviewImage: null,
      imagePreviewCloseButton: null,
      imagePreviewScale: 1,
      imagePreviewOffsetX: 0,
      imagePreviewOffsetY: 0,
      imagePreviewPointerId: null,
      imagePreviewDragStartX: 0,
      imagePreviewDragStartY: 0,
      imagePreviewDragStartOffsetX: 0,
      imagePreviewDragStartOffsetY: 0,
      imagePreviewDragMoved: false,
      imagePreviewSuppressClick: false,
      openInTab: null,
      settingsPanel: null,
      settingsCard: null,
      settingsCloseButton: null,
      settingsToggle: null,
      settingsPopoverLockedLeft: null,
      settingsPopoverLockedTop: null,
      activeLink: null,
      currentUrl: "",
      currentEntryElement: null,
      currentEntryKey: "",
      currentTopicIdHint: null,
      currentTopicTrackingKey: "",
      currentViewTracked: false,
      currentTrackRequest: null,
      currentTrackRequestKey: "",
      currentResolvedTargetPostNumber: null,
      currentFallbackTitle: "",
      currentTopic: null,
      currentTargetSpec: null,
      currentTopicAuthorUsername: "",
      currentTopicAuthorUserId: null,
      currentTitleEmojiMap: new Map(),
      currentTagIconMap: new Map(),
      replyTargetPostNumber: null,
      replyTargetLabel: "",
      replyEmojiItems: [],
      replyEmojiLoaded: false,
      abortController: null,
      loadMoreAbortController: null,
      replyAbortController: null,
      replyUploadControllers: [],
      replyUploadPendingCount: 0,
      replyUploadSerial: 0,
      replyComposerSessionId: 0,
      lastLocation: locationHref,
      settings: typeof loadSettings === "function" ? loadSettings() : {},
      topicEntriesCache: null,
      topicEntriesCacheRoot: null,
      isLoadingMorePosts: false,
      isReplySubmitting: false,
      loadMoreError: "",
      loadMoreStatus: null,
      readReportTimer: null,
      readVisibilityRaf: 0,
      readTopicId: null,
      readSeenPostNumbers: new Set(),
      lastReportedReadPostNumber: 0,
      lastReadReportKey: "",
      pendingReactionPostIds: new Set(),
      pendingBookmarkPostIds: new Set(),
      reactionOptions: [...defaultReactionOptions],
      likeReactionId: "heart",
      reactionIconMap: new Map(),
      emojiSet: "twitter",
      invalidReactionIconUrls: new Set(),
      cachedReactionOptions: typeof loadCachedReactionOptions === "function" ? loadCachedReactionOptions() : null,
      isHeaderCompact: false,
      bottomEdgeGlowArmed: true,
      bottomEdgeGlowTimer: null,
      bottomEdgeGlowLockedUntil: 0,
      jumpBackButton: null,
      jumpBackButtonTimer: null
    };
  };
})();
